// <auto-generated />
using System;
using System.Collections.Generic;
using CAF.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CAF.Migrations
{
    [DbContext(typeof(GeneralDbContext))]
    [Migration("20260211172932_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CAF.DB.Entities.ContextData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CooldownTurns")
                        .HasColumnType("integer");

                    b.Property<string>("CoreFacts")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Display")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EmbeddingUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InVectorDb")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUser")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NonverbalBehavior")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<int?>("PreviousAvailability")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("RelevanceReason")
                        .HasColumnType("text");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("SourceSessionId")
                        .HasColumnType("integer");

                    b.Property<string>("Speaker")
                        .HasColumnType("text");

                    b.Property<string>("Subtype")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenCountUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerKeywords")
                        .HasColumnType("text");

                    b.Property<int>("TriggerLookbackTurns")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerMinMatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<bool>("UseEveryTurn")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseNextTurnOnly")
                        .HasColumnType("boolean");

                    b.Property<int>("UsedLastOnTurnId")
                        .HasColumnType("integer");

                    b.Property<string>("VectorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Availability");

                    b.HasIndex("InVectorDb");

                    b.HasIndex("IsArchived");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("IsUser");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RelevanceScore");

                    b.HasIndex("SourceSessionId");

                    b.HasIndex("Speaker");

                    b.HasIndex("Type");

                    b.HasIndex("UsedLastOnTurnId");

                    b.HasIndex("VectorId");

                    b.HasIndex("ProfileId", "Type", "Availability");

                    b.HasIndex("ProfileId", "Type", "InVectorDb");

                    b.HasIndex("ProfileId", "Type", "IsUser");

                    b.HasIndex("ProfileId", "Type", "SourceSessionId");

                    b.HasIndex("ProfileId", "Availability", "IsEnabled", "IsArchived");

                    b.ToTable("ContextData");
                });

            modelBuilder.Entity("CAF.DB.Entities.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<bool>("Constant")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Constant");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Value");

                    b.ToTable("Flags");
                });

            modelBuilder.Entity("CAF.DB.Entities.LLMRequestLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CachedContentTokenCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedText")
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RawRequestJson")
                        .HasColumnType("text");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("SystemInstruction")
                        .HasColumnType("text");

                    b.Property<int>("ThinkingTokens")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<int?>("TurnId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CachedContentTokenCount");

                    b.HasIndex("DurationMs");

                    b.HasIndex("Model");

                    b.HasIndex("Provider");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("StartTime");

                    b.HasIndex("ThinkingTokens");

                    b.HasIndex("TotalCost");

                    b.HasIndex("TurnId");

                    b.HasIndex("Provider", "StartTime");

                    b.HasIndex("Provider", "Model", "StartTime");

                    b.ToTable("LLMRequestLogs");
                });

            modelBuilder.Entity("CAF.DB.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CAF.DB.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CAF.DB.Entities.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.HasIndex("ProfileId");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("CAF.DB.Entities.SystemMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsArchived");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "IsActive");

                    b.HasIndex("Type", "IsActive", "IsArchived");

                    b.ToTable("SystemMessages");
                });

            modelBuilder.Entity("CAF.DB.Entities.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("StrippedTurn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Accepted");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SessionId", "CreatedAt");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("CAF.DB.Entities.ContextData", b =>
                {
                    b.HasOne("CAF.DB.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CAF.DB.Entities.Flag", b =>
                {
                    b.HasOne("CAF.DB.Entities.Profile", "Profile")
                        .WithMany("Flags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CAF.DB.Entities.LLMRequestLogEntity", b =>
                {
                    b.HasOne("CAF.DB.Entities.Turn", "Turn")
                        .WithMany()
                        .HasForeignKey("TurnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("CAF.DB.Entities.Session", b =>
                {
                    b.HasOne("CAF.DB.Entities.Profile", "Profile")
                        .WithMany("Sessions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CAF.DB.Entities.Setting", b =>
                {
                    b.HasOne("CAF.DB.Entities.Profile", "Profile")
                        .WithMany("Settings")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CAF.DB.Entities.SystemMessage", b =>
                {
                    b.HasOne("CAF.DB.Entities.Profile", "Profile")
                        .WithMany("SystemMessages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CAF.DB.Entities.Turn", b =>
                {
                    b.HasOne("CAF.DB.Entities.Session", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CAF.DB.Entities.Profile", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("Sessions");

                    b.Navigation("Settings");

                    b.Navigation("SystemMessages");
                });

            modelBuilder.Entity("CAF.DB.Entities.Session", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
